# -*- coding: utf-8 -*-
"""Cleaning Transcripts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WInrABCEIby20to1VA1Q6_sZMrI0_M8K
"""

#https://pypi.org/project/tfrecord/
#pip install 'tfrecord[torch]'\
!pip install tfrecord[torch]
from openai import OpenAI
import pandas as pd
from google.colab import drive
import os
import ast
import shutil
from google.colab import files
from typing import List
from typing import Tuple
import numpy as np
import torch
from torch import nn
from transformers import AutoTokenizer, T5EncoderModel

class TextEmbedder(nn.Module):
    """
    Minimal wrapper around a *frozen* T5-base (or any seq-to-seq encoder).

    ────────────  Usage  ─────────────
    >>> txt = TextEmbedder("google-t5/t5-base", max_len=128)
    >>> ids, mask = txt.tokenize("some text")
    >>> z_txt    = txt.encode(torch.tensor(ids)[None, :],
                              torch.tensor(mask)[None, :])
    """
    def __init__(
        self,
        model_name: str = "google-t5/t5-base",
        max_len: int = 128,
        dtype: torch.dtype = torch.float16,   # keeps weights ≈2× smaller
    ):
        super(TextEmbedder, self).__init__()
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.encoder   = T5EncoderModel.from_pretrained(model_name).to(dtype=dtype)
        self.encoder.eval()
        for p in self.encoder.parameters():   # freeze
            p.requires_grad = False

        self.max_len = max_len

    # ------------------------------------------------------------ tokenize
    @torch.no_grad()
    def tokenize(self, text: str | List[str]) -> Tuple[np.ndarray, np.ndarray]:
        """
        padded position are set to 0, and attention mask to 1.
        For example, if max_len=5 and text="hellow world",
        the tokenizer will return:
        input_ids = [21820, 296,  0,  0,  0]
        attention_mask = [1, 1, 0, 0, 0]

        Returns  (input_ids[int32], attn_mask[int8])  shaped (max_len,)
        (If *text* is a list, shapes are (B,max_len).)
        """
        batch = self.tokenizer(
            text,
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_attention_mask=True,
        )
        ids   = np.asarray(batch["input_ids"],   dtype=np.int32)
        mask  = np.asarray(batch["attention_mask"], dtype=np.int8)
        return ids, mask

    # ------------------------------------------------------------ encode
    @torch.no_grad()
    def encode(
        self,
        input_ids: torch.LongTensor,        # (B,L)
        attention_mask: torch.BoolTensor,   # (B,L)
    ) -> torch.Tensor:                      # (B,L,H)
        """
        Run the frozen encoder and return the sequence embeddings
        (no pooling – do that in your SigLIP loss if you wish).
        """
        input_ids     = input_ids
        attention_mask = attention_mask

        out = self.encoder(input_ids=input_ids,
                           attention_mask=attention_mask,
                           return_dict=True)
        return out.last_hidden_state        # (B,L,hidden)

#reading data into *dfs*
drive.mount('/content/drive')
folder_path_transcription = '/content/drive/MyDrive/Transcription_GoogleSpeechModel_XinxinCopy/Transcription'
transcripts = sorted([f for f in os.listdir(folder_path_transcription) if f.endswith('.csv')])
folder_path_time = '/content/drive/MyDrive/Transcription_GoogleSpeechModel_XinxinCopy/Cleaned_Time_Converted'
cleaned_time = sorted([f for f in os.listdir(folder_path_time) if f.endswith('.csv')])

all_transcripts = []
for file in transcripts:
  df = pd.read_csv(os.path.join(folder_path_transcription,file))
  grouped = (
    df
    .groupby('File', sort=False)['Transcript']
    .apply(lambda x: ''.join(x.dropna()))
    .reset_index()
)
  grouped['OG_CSV'] = file
  all_transcripts.append(grouped)

print(all_transcripts[2])

all_images = []
for file in cleaned_time:
  #row 1 is tutorial
  df = pd.read_csv(os.path.join(folder_path_time,file))
  df = df.drop(index=0)
  df = df.reset_index(drop=True)
  df = df[['patient_id','text', 'image_number']].copy()
  df['OG_CSV'] = file
  all_images.append(df)

all_images[0]

print(f"File: {file}")
print(df.head(3))
print(df.index)

i=3
print(all_images[i].head(50))
print("*"*100)
print(all_transcripts[i].head(50))

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import re
def patient_image(patient_id, image_number):
    match = re.match(r"([a-zA-Z]+)(\d+)", patient_id)
    if not match:
        print(f"Invalid patient_id format: {patient_id}")
        return None

    letter_part, number_part = match.groups()
    number_part = int(number_part)
    folder_path = '/content/drive/MyDrive/Transcription_GoogleSpeechModel_XinxinCopy/Images'

    # Try both OD and OS
    for eye in ["OD", "OS"]:
        file_name = f"{number_part}_{image_number}_{eye}.tiff_3channel.png"
        print(f"Checking for file: {file_name}")

        for root, dirs, files in os.walk(folder_path):
            if file_name in files:
                file_path = os.path.join(root, file_name)
                print(f"Found file: {file_path}")
                img = mpimg.imread(file_path)
                plt.imshow(img)
                plt.axis('off')
                # plt.show()  # Uncomment if you want to display the image
                with open(file_path, 'rb') as f:
                    png_bytes = f.read()
                    return png_bytes,letter_part, file_name

    print(f"No image found for patient {patient_id}, image number {image_number}")
    return None, letter_part, None

all_data_df = pd.concat(all_images)

#function to clean transcripts
client = OpenAI(api_key=)
def clean(text):
  response = client.chat.completions.create(
      model="gpt-4o-mini",
      messages=[
          {"role": "system", "content": (
              "You are a glaucoma specialist reviewing a clinician’s spoken transcript as they interpret an OCT report. Your task is to clean up the transcript by making it "
              "grammatically correct, coherent, and medically accurate.\n\n"
              "Preserve:\n"
              "- The speaker’s original clinical intent\n"
              "- Any medically relevant language or observations\n\n"
              "Ignore filler words, hesitations, and false starts. Do not change clinical meaning. Your output should read like a fluent, professional clinical summary of what was said."
          )},
          {"role": "user", "content": (
              f"Please clean up the following transcript. Make it readable and medically precise, while preserving the speaker’s intent and any clinical content. "
              f"Output only the cleaned transcript.\n\nTranscript:\n{text}"
          )}
      ],
      temperature=0.8,
      max_tokens=1000
    )

  return response.choices[0].message.content

#function to clean transcripts for VQA
client = OpenAI(api_key="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")
def VQAclean(text, caption, label):
  response = client.chat.completions.create(
      model="gpt-4o-mini",
      messages=[
        {"role": "system", "content": (
            "You are an expert retina specialist and medical AI researcher. Your task is to generate a clinically sound and image-grounded explanation for a Visual Question Answering (VQA) model that interprets OCT eye scans.\n\n"
            "You are given:\n"
            "- A raw transcript from a retina specialist. It may contain noise, hesitations, or incomplete thoughts.\n"
            "- A caption that may describe or summarize the OCT image more coherently.\n"
            "Your explanation should be medically accurate and concise. If the transcript contains relevant clinical insights, incorporate them. "
            "If the transcript is nonsensical, unclear, or uninformative, prioritize the caption and the label. "
            "The goal is to produce a medically grounded explanation suitable for training a VQA model or for presentation to another clinician."
        )},
        #consider writing "Opthalomogist (retina specialis)" (referring to a medical doctor) and look at results
        {"role": "user", "content": (
            f"Here is the data for one OCT scan:\n\n"
            f"Transcript:\n{text}\n\n"
            f"Caption:\n{caption}\n\n"
            f"Please generate a clear, clinical explanation based on this information. Prioritize the most informative and medically relevant content. Output only the explanation."
        )}
    ],
      temperature=0.8,
      max_tokens=1000
    )

  return response.choices[0].message.content

modify = []
for image_index, image in enumerate(all_images):
  for row_index, row in image.iterrows():
    patient_id = str(row['patient_id'])
    image_number = str(row['image_number'])
    image_bytes, wet_normal, image_file = patient_image(patient_id, image_number)
    all_transcripts[image_index].at[row_index, 'image_data'] = image_bytes
    all_transcripts[image_index].at[row_index, 'class'] = wet_normal
    all_transcripts[image_index].at[row_index, 'patient_id'] = patient_id
    all_transcripts[image_index].at[row_index, 'image_number'] = image_number
    all_transcripts[image_index].at[row_index, 'image_file'] = image_file
    all_transcripts[image_index].at[row_index, 'OG_CSV'] = row['OG_CSV']
    all_transcripts[image_index].at[row_index, 'text'] = row['text']

for transcript_index, transcript in enumerate(all_transcripts):
  for row_index, row in transcript.iterrows():
    text = str(row['Transcript'])
    label = str(row['class'])
    caption = str(row['text'])
    cleaned_text = clean(text)
    VQA_text = VQAclean(cleaned_text, caption, label)
    all_transcripts[transcript_index].at[row_index, 'Cleaned_Transcript'] = cleaned_text
    all_transcripts[transcript_index].at[row_index, 'VQA_Transcript'] = VQA_text

all_transcripts[2].head(100)

combined_df = pd.concat(all_transcripts, ignore_index=True)
combined_df.iloc[::10]

embedder = TextEmbedder("google-t5/t5-base",max_len = 128)
cleaned_texts = combined_df["Cleaned_Transcript"].tolist()
ids_np, mask_np = embedder.tokenize(cleaned_texts)
combined_df["Cleaned_input_ids"] = ids_np.tolist()
combined_df["Cleaned_attn_mask"] = mask_np.tolist()
VQA_texts = combined_df["VQA_Transcript"].tolist()
ids_np, mask_np = embedder.tokenize(VQA_texts)
combined_df["VQA_input_ids"] = ids_np.tolist()
combined_df["VQA_attn_mask"] = mask_np.tolist()

#checking ideal tokenizer length
first_zero_indices = []

for mask in combined_df["VQA_attn_mask"]:
    if isinstance(mask, list):
        try:
            first_zero = mask.index(0)
            first_zero_indices.append(first_zero)
        except ValueError:
            continue  # skip if 0 is not in the list

if first_zero_indices:
    print("Max of first-zero indices:", max(first_zero_indices))
else:
    print("No zero found in any row.")

#standardizing images
import io
decoded_images = []
valid_indices = []
for i,b in enumerate(combined_df['image_data']):
  if isinstance(b,bytes):
    try:
      img = mpimg.imread(io.BytesIO(b)).astype(np.float32)
      if img.max() > 1.0:
        img = img/255.0
      decoded_images.append(img)
      valid_indices.append(i)
    except Exception as e:
      print(f"Failed to decode image at index {i}: {e}")
img_stack = np.stack(decoded_images)
global_mean = img_stack.mean(axis=(0,1,2))
global_std = img_stack.std(axis=(0,1,2))
np.save("global_mean.npy", global_mean)
np.save("global_std.npy", global_std)
print(global_mean)
print(global_std)
#global_mean = np.load("global_mean.npy")
#global_std = np.load("global_std.npy")
normalized_images = []

for img in decoded_images:
    norm_img = (img - global_mean) / global_std
    normalized_images.append(norm_img.astype(np.float32))
combined_df["normalized_image"] = np.nan
for df_idx, norm_img in zip(valid_indices, normalized_images):
    combined_df.at[df_idx, "normalized_image"] = norm_img.astype(np.float32).tobytes()

import pandas as pd
combined_df.to_pickle("/tmp/combined_df.pkl")

!pip uninstall -y tensorflow
#restart runtime

import os
import numpy as np
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"

!pip install -q tfrecord[torch]

import pandas as pd
combined_df = pd.read_pickle("/tmp/combined_df.pkl")

import tfrecord
clean_df = combined_df.dropna(subset=["normalized_image"])

writer_text = tfrecord.TFRecordWriter("/tmp/Transcript.tfrecord")
writer_VQA = tfrecord.TFRecordWriter("/tmp/VQA.tfrecord")

for _, row in clean_df.iterrows():
    clean_input_ids = row["Cleaned_input_ids"]
    clean_attn_mask = row["Cleaned_attn_mask"]
    class_label = row["class"]
    image_data = row["normalized_image"]
    VQA_input_ids = row["VQA_input_ids"]
    VQA_attn_mask = row["VQA_attn_mask"]
    if isinstance(image_data, bytes) and isinstance(class_label, str):
        text_record = {
            "input_ids": (np.array(clean_input_ids, dtype=np.int64), "int"),
            "attn_mask": (np.array(clean_attn_mask, dtype=np.int64), "int"),
            "class": (class_label.encode("utf-8"), "byte"),
            "normalized_image": (image_data, "byte")
        }
        writer_text.write(text_record)
        VQA_record = {
            "input_ids": (np.array(VQA_input_ids, dtype=np.int64), "int"),
            "attn_mask": (np.array(VQA_attn_mask, dtype=np.int64), "int"),
            "class": (class_label.encode("utf-8"), "byte"),
            "normalized_image": (image_data, "byte")
        }
        writer_VQA.write(VQA_record)


writer_text.close()
writer_VQA.close()

clean_df.head()

from tfrecord import tfrecord_loader

description = {
    "input_ids": "int",
    "attn_mask": "int",
    "class": "byte",
    "normalized_image": "byte"
}

loader_text = tfrecord_loader("/tmp/Transcript.tfrecord", None, description)
loader_VQA = tfrecord_loader("/tmp/VQA.tfrecord", None, description)

for record_text, record_VQA in zip(loader_text,loader_VQA):
    input_ids_text = record_text["input_ids"].tolist()
    attn_mask_text = record_text["attn_mask"].tolist()
    class_label_text = record_text["class"].decode("utf-8")
    input_ids_VQA = record_VQA["input_ids"].tolist()
    attn_mask_VQA = record_VQA["attn_mask"].tolist()
    class_label_VQA = record_VQA["class"].decode("utf-8")
    image_bytes = record_VQA["normalized_image"]

    print("Text Input IDs:", input_ids_text[:10])
    print("VQA Input IDs:", input_ids_VQA[:10])
    print("Label:", class_label_text)
    print("Image bytes (Text):", len(image_bytes))
    print("=" * 40)

import shutil
from google.colab import files
shutil.copy("/tmp/Transcript.tfrecord", "Transcript.tfrecord")
files.download("Transcript.tfrecord")
shutil.copy("/tmp/VQA.tfrecord", "VQA.tfrecord")
files.download("VQA.tfrecord")
subset = clean_df[["Transcript", "Cleaned_Transcript", "VQA_Transcript", "File", "image_file","patient_id", "image_number"]]
subset.to_csv("/tmp/subset_clean_df.csv", index=False)
files.download("/tmp/subset_clean_df.csv")

#once you've written the file, put it on the server. Use this link: https://filezilla-project.org/download.php?type=client