# -*- coding: utf-8 -*-
"""Cleaning Transcripts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WInrABCEIby20to1VA1Q6_sZMrI0_M8K
"""

#https://pypi.org/project/tfrecord/
#pip install 'tfrecord[torch]'\
!pip install tfrecord[torch]
from openai import OpenAI
import pandas as pd
from google.colab import drive
import os
import ast
import shutil
from google.colab import files
from typing import List
from typing import Tuple
import numpy as np
import torch
from torch import nn
from transformers import AutoTokenizer, T5EncoderModel

class TextEmbedder(nn.Module):
    """
    Minimal wrapper around a *frozen* T5-base (or any seq-to-seq encoder).

    ────────────  Usage  ─────────────
    >>> txt = TextEmbedder("google-t5/t5-base", max_len=128)
    >>> ids, mask = txt.tokenize("some text")
    >>> z_txt    = txt.encode(torch.tensor(ids)[None, :],
                              torch.tensor(mask)[None, :])
    """
    def __init__(
        self,
        model_name: str = "google-t5/t5-base",
        max_len: int = 128,
        dtype: torch.dtype = torch.float16,   # keeps weights ≈2× smaller
    ):
        super(TextEmbedder, self).__init__()
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)
        self.encoder   = T5EncoderModel.from_pretrained(model_name).to(dtype=dtype)
        self.encoder.eval()
        for p in self.encoder.parameters():   # freeze
            p.requires_grad = False

        self.max_len = max_len

    # ------------------------------------------------------------ tokenize
    @torch.no_grad()
    def tokenize(self, text: str | List[str]) -> Tuple[np.ndarray, np.ndarray]:
        """
        padded position are set to 0, and attention mask to 1.
        For example, if max_len=5 and text="hellow world",
        the tokenizer will return:
        input_ids = [21820, 296,  0,  0,  0]
        attention_mask = [1, 1, 0, 0, 0]

        Returns  (input_ids[int32], attn_mask[int8])  shaped (max_len,)
        (If *text* is a list, shapes are (B,max_len).)
        """
        batch = self.tokenizer(
            text,
            padding="max_length",
            truncation=True,
            max_length=self.max_len,
            return_attention_mask=True,
        )
        ids   = np.asarray(batch["input_ids"],   dtype=np.int32)
        mask  = np.asarray(batch["attention_mask"], dtype=np.int8)
        return ids, mask

    # ------------------------------------------------------------ encode
    @torch.no_grad()
    def encode(
        self,
        input_ids: torch.LongTensor,        # (B,L)
        attention_mask: torch.BoolTensor,   # (B,L)
    ) -> torch.Tensor:                      # (B,L,H)
        """
        Run the frozen encoder and return the sequence embeddings
        (no pooling – do that in your SigLIP loss if you wish).
        """
        input_ids     = input_ids
        attention_mask = attention_mask

        out = self.encoder(input_ids=input_ids,
                           attention_mask=attention_mask,
                           return_dict=True)
        return out.last_hidden_state        # (B,L,hidden)

#reading data into *dfs*
drive.mount('/content/drive')
folder_path_transcription = '/content/drive/MyDrive/Transcription_GoogleSpeechModel_XinxinCopy/Transcription'
transcripts = sorted([f for f in os.listdir(folder_path_transcription) if f.endswith('.csv')])
folder_path_time = '/content/drive/MyDrive/Transcription_GoogleSpeechModel_XinxinCopy/Cleaned_Time_Converted'
cleaned_time = sorted([f for f in os.listdir(folder_path_time) if f.endswith('.csv')])

all_transcripts = []
for file in transcripts:
  df = pd.read_csv(os.path.join(folder_path_transcription,file))
  grouped = (
    df
    .groupby('File', sort=False)['Transcript']
    .apply(lambda x: ''.join(x.dropna()))
    .reset_index()
)
  grouped['OG_CSV'] = file
  all_transcripts.append(grouped)

all_images = []
for file in cleaned_time:
  #row 1 is tutorial
  df = pd.read_csv(os.path.join(folder_path_time,file))
  df = df.drop(index=0)
  df = df.reset_index(drop=True)
  df = df[['patient_id','text', 'image_number']].copy()
  df['OG_CSV'] = file
  all_images.append(df)

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import re
def patient_image(patient_id, image_number):
    match = re.match(r"([a-zA-Z]+)(\d+)", patient_id)
    if not match:
        print(f"Invalid patient_id format: {patient_id}")
        return None

    letter_part, number_part = match.groups()
    number_part = int(number_part)
    folder_path = '/content/drive/MyDrive/Transcription_GoogleSpeechModel_XinxinCopy/Images'

    # Try both OD and OS
    for eye in ["OD", "OS"]:
        file_name = f"{number_part}_{image_number}_{eye}.tiff_3channel.png"
        print(f"Checking for file: {file_name}")

        for root, dirs, files in os.walk(folder_path):
            if file_name in files:
                file_path = os.path.join(root, file_name)
                print(f"Found file: {file_path}")
                img = mpimg.imread(file_path)
                plt.imshow(img)
                plt.axis('off')
                # plt.show()  # Uncomment if you want to display the image
                with open(file_path, 'rb') as f:
                    png_bytes = f.read()
                    return png_bytes,letter_part, file_name

    print(f"No image found for patient {patient_id}, image number {image_number}")
    return None, letter_part, None

all_data_df = pd.concat(all_images)

#function to clean transcripts for VQA
client = OpenAI(api_key="")
def VQAclean(text, caption, label):
 response = client.chat.completions.create(
     model="gpt-4o",
     messages=[
       {"role": "system", "content": (
           "You are an expert ophthalmologist (retina specialist) and medical AI researcher. Your task is to generate a concise, clinically sound and image-grounded explanation for a Visual Question Answering (VQA) model that interprets OCT eye scans.\n\n"
           "You are given:\n"
           "- A raw transcript from a retina specialist. It may contain noise, hesitations, or incomplete thoughts.\n"
           "- A descriptive caption that may describe or summarize the OCT image more coherently.\n"
           "Instructions:\n"
           "- Prioritize clinical accuracy and clarity.\n"
           "- If the transcript contains meaningful clinical insight, incorporate it into the explanation.\n"
           "- If the transcript lacks clinical value (e.g., hesitations, irrelevant comments), focus on the caption and label to construct a coherent explanation.\n"
           "- Do not repeat the raw input. Output only a final explanation that could plausibly come from a retina specialist reviewing the scan."
       )},
       {"role": "user", "content": (
           f"Here is the data for one OCT scan:\n\n"
           f"Transcript:\n{text}\n\n"
           f"Caption:\n{caption}\n\n"
           f"Please generate a clear, clinical explanation based on this information that is suitable for another ophthalmologist or for training a medical AI model. Prioritize the most informative and medically relevant content. Output only the explanation."
       )}
   ],
     temperature=0.8,
     max_tokens=1000
   )


 return response.choices[0].message.content

modify = []
for image_index, image in enumerate(all_images):
  for row_index, row in image.iterrows():
    patient_id = str(row['patient_id'])
    image_number = str(row['image_number'])
    image_bytes, wet_normal, image_file = patient_image(patient_id, image_number)
    all_transcripts[image_index].at[row_index, 'image_data'] = image_bytes
    all_transcripts[image_index].at[row_index, 'class'] = wet_normal
    all_transcripts[image_index].at[row_index, 'patient_id'] = patient_id
    all_transcripts[image_index].at[row_index, 'image_number'] = image_number
    all_transcripts[image_index].at[row_index, 'image_file'] = image_file
    all_transcripts[image_index].at[row_index, 'OG_CSV'] = row['OG_CSV']
    all_transcripts[image_index].at[row_index, 'text'] = row['text']
for df in all_transcripts:
    df["VQA_Transcript"] = None
for transcript_index, transcript in enumerate(all_transcripts):
  for row_index, row in transcript.iterrows():
    text = str(row['Transcript'])
    label = str(row['class'])
    caption = str(row['text'])

    explanations = []
    for i in range (8):
      explanation = VQAclean(text, caption, label)
      explanations.append(explanation)
    all_transcripts[transcript_index].at[row_index, 'VQA_Transcript'] = explanations

combined_df = pd.concat(all_transcripts, ignore_index=True)
combined_df.iloc[::10]

embedder = TextEmbedder("google-t5/t5-base",max_len = 128)

VQA_input_ids_list = []
VQA_attn_mask_list = []
for explanations in combined_df["VQA_Transcript"]:
    input_ids_list = []
    attn_mask_list = []
    for explanation in explanations:
        ids_np, mask_np = embedder.tokenize(explanation)
        input_ids_list.append(ids_np)
        attn_mask_list.append(mask_np)
    VQA_input_ids_list.append(input_ids_list)
    VQA_attn_mask_list.append(attn_mask_list)
combined_df["VQA_input_ids"] = VQA_input_ids_list
combined_df["VQA_attn_mask"] = VQA_attn_mask_list

#standardizing images
import io
decoded_images = []
valid_indices = []
for i,b in enumerate(combined_df['image_data']):
  if isinstance(b,bytes):
    try:
      img = mpimg.imread(io.BytesIO(b)).astype(np.float32)
      if img.max() > 1.0:
        img = img/255.0
      decoded_images.append(img)
      valid_indices.append(i)
    except Exception as e:
      print(f"Failed to decode image at index {i}: {e}")
img_stack = np.stack(decoded_images)
global_mean = img_stack.mean(axis=(0,1,2))
global_std = img_stack.std(axis=(0,1,2))
np.save("global_mean.npy", global_mean)
np.save("global_std.npy", global_std)
print(global_mean)
print(global_std)
#global_mean = np.load("global_mean.npy")
#global_std = np.load("global_std.npy")
normalized_images = []

for img in decoded_images:
    norm_img = (img - global_mean) / global_std
    normalized_images.append(norm_img.astype(np.float32))
combined_df["normalized_image"] = np.nan
for df_idx, norm_img in zip(valid_indices, normalized_images):
    combined_df.at[df_idx, "normalized_image"] = norm_img.astype(np.float32).tobytes()

import pandas as pd
combined_df.to_pickle("/tmp/combined_df.pkl")

!pip uninstall -y tensorflow
#restart runtime

import os
import numpy as np
os.environ["PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION"] = "python"

!pip install -q tfrecord[torch]

import pandas as pd
combined_df = pd.read_pickle("/tmp/combined_df.pkl")

import tfrecord
clean_df = combined_df.dropna(subset=["normalized_image"]).copy()

writer_VQA = tfrecord.TFRecordWriter("/tmp/VQA.tfrecord")

for _, row in clean_df.iterrows():
    class_label = row["class"]
    image_data = row["normalized_image"]
    VQA_input_ids = row["VQA_input_ids"]
    VQA_attn_mask = row["VQA_attn_mask"]
    if isinstance(image_data, bytes) and isinstance(class_label, str):
      VQA_record = {
          "input_ids": (np.array(VQA_input_ids, dtype=np.int64).flatten(), "int"), #shape (8, max_len)
          "input_ids_shape": (np.array(VQA_input_ids, dtype=np.int64).shape, "int"),
          "attn_mask_shape": (np.array(VQA_attn_mask, dtype=np.int64).shape, "int"),
          "attn_mask": (np.array(VQA_attn_mask, dtype=np.int64).flatten(), "int"),
          "class": (class_label.encode("utf-8"), "byte"),
          "normalized_image": (image_data, "byte")
      }
      writer_VQA.write(VQA_record)
writer_VQA.close()

clean_df.head()

from tfrecord import tfrecord_loader

description = {
    "input_ids": "int",
    "attn_mask": "int",
    "class": "byte",
    "normalized_image": "byte"
}

loader_VQA = tfrecord_loader("/tmp/VQA.tfrecord", None, description)

for record_VQA in loader_VQA:
  input_ids_VQA = record_VQA["input_ids"].tolist()
  attn_mask_VQA = record_VQA["attn_mask"].tolist()
  class_label_VQA = record_VQA["class"].decode("utf-8")
  image_bytes = record_VQA["normalized_image"]

import shutil
from google.colab import files
shutil.copy("/tmp/VQA.tfrecord", "VQA.tfrecord")
files.download("VQA.tfrecord")

vqa_cols = [f"VQA_Transcripts{i+1}" for i in range(8)]
clean_df[vqa_cols] = pd.DataFrame(clean_df["VQA_Transcript"].tolist(), index=clean_df.index)
clean_df.drop(columns=["VQA_Transcript"], inplace=True)
subset = clean_df[["Transcript"] + vqa_cols + ["File", "image_file","patient_id", "image_number"]]
subset.to_csv("/tmp/subset_clean_df.csv", index=False)
files.download("/tmp/subset_clean_df.csv")